/********************************************************************
 This file was generated by menu Tool of Rockchip Co., Ltd.

 Generate time: 2018-7-18 16:6:39

 Tool Version: 3.0.0.0

 End.
********************************************************************/
#ifndef          _MENU_RESOURCE_H
#define          _MENU_RESOURCE_H


#define          MENU_ITEM_LENGTH            (unsigned short)254             // The length of menu item in bytes
#define          TOTAL_MENU_ITEM             (unsigned short)223
#define          TOTAL_LANAUAGE_NUM          (unsigned short)19
#define          MAX_SUBMENU_NUM             (unsigned short)19
#define          MENU_CONTENT_OFFSET         (unsigned short)54





#define          SID_MUSIC                                        (unsigned short)0x0000       //Music
#define          SID_RADIO                                        (unsigned short)0x0001       //Radio
#define          SID_RECORD                                       (unsigned short)0x0002       //Record
#define          SID_TEXT                                         (unsigned short)0x0003       //Text
#define          SID_EXPLORER                                     (unsigned short)0x0004       //Explorer
#define          SID_MAIN_SETTINGS                                (unsigned short)0x0005       //Settings
#define          SID_VIDEO                                        (unsigned short)0x0006       //Video
#define          SID_PHOTO                                        (unsigned short)0x0007       //Photo
#define          SID_FM_RADIO                                     (unsigned short)0x0008       //FM Radio 
#define          SID_GAME                                         (unsigned short)0x0009       //Game
#define          SID_NOR                                          (unsigned short)0x000a       //NOR
#define          SID_ROCK                                         (unsigned short)0x000b       //ROCK
#define          SID_POP                                          (unsigned short)0x000c       //POP
#define          SID_CLASS                                        (unsigned short)0x000d       //CLASS
#define          SID_BASS                                         (unsigned short)0x000e       //BASS
#define          SID_JAZZ                                         (unsigned short)0x000f       //JAZZ
#define          SID_USER                                         (unsigned short)0x0010       //USER
#define          SID_UNKNOWN                                      (unsigned short)0x0011       //~Unknown~
#define          SID_NO_LYRIC_FILE                                (unsigned short)0x0012       //~No Lyric File~
#define          SID_MANUAL                                       (unsigned short)0x0013       //Manual
#define          SID_PRESET                                       (unsigned short)0x0014       //Preset
#define          SID_MEM                                          (unsigned short)0x0015       //Add Preset
#define          SID_DEL                                          (unsigned short)0x0016       //Delete Preset
#define          SID_AUTO                                         (unsigned short)0x0017       //Auto Preset
#define          SID_REC                                          (unsigned short)0x0018       //FM Record
#define          SID_PLAY_REC_DATA                                (unsigned short)0x0019       //Play Rec Data
#define          SID_DELETE_REC_DATA                              (unsigned short)0x001a       //Delete Rec Data
#define          SID_DELETE_ALL                                   (unsigned short)0x001b       //Delete All
#define          SID_ALL_REC_DATA                                 (unsigned short)0x001c       //All Rec Data
#define          SID_DELETE_ALL_COMFIRM                           (unsigned short)0x001d       //Delete All?
#define          SID_DELETING                                     (unsigned short)0x001e       //Deleting…
#define          SID_SAVE_CHANNEL                                 (unsigned short)0x001f       //Replace OK?  
#define          SID_DELETE_CHANNEL                               (unsigned short)0x0020       //Delete OK?
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x0021       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x0022       //Load BookMark
#define          SID_MIC_REC                                      (unsigned short)0x0023       //MIC REC
#define          SID_LINE_IN_REC                                  (unsigned short)0x0024       //LINE IN REC
#define          SID_FM_REC                                       (unsigned short)0x0025       //FM REC
#define          SID_RECORDING                                    (unsigned short)0x0026       //Recording...
#define          SID_RECORD_PAUSE                                 (unsigned short)0x0027       //Pause...
#define          SID_RECORD_PREPARE                               (unsigned short)0x0028       //Prepare...
#define          SID_RECORD_SAVE_FILE                             (unsigned short)0x0029       //Save File...
#define          SID_CREAT_FILE_ERROR                             (unsigned short)0x002a       //Creat File Error!
#define          SID_DISK_IS_FULL                                 (unsigned short)0x002b       //Disk Is Full!
#define          SID_FLASH_MEMERY                                 (unsigned short)0x002c       //Flash Memery
#define          SID_MINISD_CARD                                  (unsigned short)0x002d       //MiniSD Card 
#define          SID_COULD_NOT_CONTINUE                           (unsigned short)0x002e       //Could not continue
#define          SID_WARNING                                      (unsigned short)0x002f       //Warning
#define          SID_YES                                          (unsigned short)0x0030       //Yes
#define          SID_NO                                           (unsigned short)0x0031       //No
#define          SID_EXIT                                         (unsigned short)0x0032       //Exit
#define          SID_PLEASE_WAIT                                  (unsigned short)0x0033       //Please Wait……
#define          SID_LOW_BATTERY                                  (unsigned short)0x0034       //Low Battery!
#define          SID_FIRMWARE_UPGRADE                             (unsigned short)0x0035       //Firmware Upgrade?
#define          SID_PLEASE_INSERT_USB                            (unsigned short)0x0036       //Connect USB…… 
#define          SID_RESTORE_DEFAULT_VAL                          (unsigned short)0x0037       //Restorable?
#define          SID_FORMAT_DISK                                  (unsigned short)0x0038       //Format Disk?
#define          SID_FORMATTING                                   (unsigned short)0x0039       //Formatting……
#define          SID_FILE_FORMAT_ERROR                            (unsigned short)0x003a       //File Format Error!
#define          SID_NO_MUSIC_FILE                                (unsigned short)0x003b       //No Music File!
#define          SID_DELETE_FILE                                  (unsigned short)0x003c       //Delete File
#define          SID_DELETE_FILE_ASK                              (unsigned short)0x003d       //Delete File?
#define          SID_DELETING_FILE                                (unsigned short)0x003e       //Deleting File…… 
#define          SID_MUSIC_FILE                                   (unsigned short)0x003f       //Music File
#define          SID_VIDEO_FILE                                   (unsigned short)0x0040       //Video File
#define          SID_TEXT_FILE                                    (unsigned short)0x0041       //Text
#define          SID_PICTURE_FILE                                 (unsigned short)0x0042       //Picture File
#define          SID_EXPLORER                                     (unsigned short)0x0043       //Explorer
#define          SID_C_FLASH                                      (unsigned short)0x0044       //C:FLASH
#define          SID_D_FLASH                                      (unsigned short)0x0045       //D:FLASH
#define          SID_D_SD_CARD                                    (unsigned short)0x0046       //D:SD CARD
#define          SID_E_SD_CARD                                    (unsigned short)0x0047       //E:SD CARD
#define          SID_NO_FILE                                      (unsigned short)0x0048       //No File!
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x0049       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x004a       //Load BookMark
#define          SID_WRITE_FILE_ERROR                             (unsigned short)0x004b       //Write File Error!
#define          SID_CLOSE_FILE_ERROR                             (unsigned short)0x004c       //Close File Error!
#define          SID_MEDIALIB                                     (unsigned short)0x004d       //medialib
#define          SID_PLAYING                                      (unsigned short)0x004e       //Go to playback screen.
#define          SID_ALL_MUISC_FILE                               (unsigned short)0x004f       //All Songs
#define          SID_ARTIST                                       (unsigned short)0x0050       //Artists
#define          SID_ALBUM                                        (unsigned short)0x0051       //Albums
#define          SID_GENRE                                        (unsigned short)0x0052       //Genres
#define          SID_PLAY_LIST                                    (unsigned short)0x0053       //Playlist
#define          SID_DIR_LIST                                     (unsigned short)0x0054       //Folder
#define          SID_RECORE_FILE                                  (unsigned short)0x0055       //RECORE FILE
#define          SID_MY_FAVORITE                                  (unsigned short)0x0056       //My Favorite
#define          SID_UPDATE_MEDIALIB                              (unsigned short)0x0057       //MediaLib Update
#define          SID_UPDATEING_FIRMWARE                           (unsigned short)0x0058       //Firmware Upgrading…… 
#define          SID_RECOVER_FIRMWARE                             (unsigned short)0x0059       //Firmware Recoverying…… 
#define          SID_HOLDON_PLAY                                  (unsigned short)0x005a       //Breakpoint player
#define          SID_TITLE                                        (unsigned short)0x005b       //Title
#define          SID_ADD_FAVORITE                                 (unsigned short)0x005c       //Add To Favorite
#define          SID_CLEAR_FAVORITE                               (unsigned short)0x005d       //Clear Up
#define          SID_UPDATEING_MEDIALIB                           (unsigned short)0x005e       //MediaLib Update…… 
#define          SID_CONNECTING_USB                               (unsigned short)0x005f       //Connecting USB
#define          SID_CHARGING                                     (unsigned short)0x0060       //Charging
#define          SID_FULL_CHANGED                                 (unsigned short)0x0061       //Fully charged
#define          SID_CANNOT_CHARGE                                (unsigned short)0x0062       //Cannot charge
#define          SID_DATA_EX_NOT_DISCONNECT_LINE1                 (unsigned short)0x0063       //Do not
#define          SID_DATA_EX_NOT_DISCONNECT_LINE2                 (unsigned short)0x0064       //disconnect
#define          SID_DATA_EX_NOT_DISCONNECT_LINE3                 (unsigned short)0x0065       //
#define          SID_VOLUME                                       (unsigned short)0x0066       //Volume
#define          SID_UPDATING_LIBRARY                             (unsigned short)0x0067       //Updating Library
#define          SID_AVLS                                         (unsigned short)0x0068       //AVLS
#define          SID_VOLUME_LIMIT_LINE1                           (unsigned short)0x0069       //Check The
#define          SID_VOLUME_LIMIT_LINE2                           (unsigned short)0x006a       //Volume Level
#define          SID_BLUETOOTH                                    (unsigned short)0x006b       //Bluetooth
#define          SID_BT_STATUS                                    (unsigned short)0x006c       //Status:
#define          SID_BT_PAIRING                                   (unsigned short)0x006d       //Pairing……
#define          SID_BT_PAIR_SUCCESS                              (unsigned short)0x006e       //Pair Success
#define          SID_BT_POWERON                                   (unsigned short)0x006f       //Power On
#define          SID_BT_POWEROFF                                  (unsigned short)0x0070       //Power Off
#define          SID_BT_A2DP_PAUSE                                (unsigned short)0x0071       //A2DP Pause
#define          SID_BT_A2DP_PLAY                                 (unsigned short)0x0072       //A2DP Play
#define          SID_BT_CALL_REMIND                               (unsigned short)0x0073       //Call Remind
#define          SID_BT_TALKING                                   (unsigned short)0x0074       //Taking
#define          SID_BT_CONNECTING                                (unsigned short)0x0075       //BT Connecting
#define          SID_BT_CONNECTING_OK                             (unsigned short)0x0076       //Connecting Succeed
#define          SID_BT_DISCONNECT                                (unsigned short)0x0077       //Disconnect
#define          SID_BT_CONNECTING_FAIL                           (unsigned short)0x0078       //Connecting Fail
#define          SID_BT_SCANING                                   (unsigned short)0x0079       //Scaning
#define          SID_BT_DISCONNECT_CUR_DEV                        (unsigned short)0x007a       //Disconnect  Dev ？
#define          SID_BT_DELETE_DEV                                (unsigned short)0x007b       //Delete Dev ？
#define          SID_BT_CONNECT_CANNCELING                        (unsigned short)0x007c       //Connect Canceling
#define          SID_BT_CONNECT_CANCEL_COMPLETE                   (unsigned short)0x007d       //Cancel Complete
//-----------------------------------------------------------------------------------------------------------------------------
//-------This is a menu-------
#define          SID_SETTINGS                                     (unsigned short)0x007e       //Settings
#define          SID_SETTING_MUSIC                                (unsigned short)0x007f       //Music Settings
#define          SID_MUSIC_SHUFFLE                                (unsigned short)0x0080       //Shuffle
#define          SID_MUSIC_SHUFFLE_OFF                            (unsigned short)0x0081       //Shuffle Off           [Function Index: 0000]
#define          SID_MUSIC_SHUFFLE_ON                             (unsigned short)0x0082       //Shuffle On            [Function Index: 0001]
#define          SID_MUSIC_REPEAT_MODE                            (unsigned short)0x0083       //Repeat
#define          SID_MUSIC_FOLDER_ONCE                            (unsigned short)0x0084       //Off                   [Function Index: 0002]
#define          SID_MUSIC_FOLDER_REPEAT                          (unsigned short)0x0085       //Repeat                [Function Index: 0003]
#define          SID_MUSIC_REPEAT_ONE                             (unsigned short)0x0086       //Repeat 1 Song         [Function Index: 0004]
#define          SID_EQ_SELECT                                    (unsigned short)0x0087       //Equalizer
#define          SID_EQ_BASS                                      (unsigned short)0x0088       //BASS                  [Function Index: 0005]
#define          SID_EQ_HEAVY                                     (unsigned short)0x0089       //Heavy                 [Function Index: 0006]
#define          SID_EQ_POP                                       (unsigned short)0x008a       //Pop                   [Function Index: 0007]
#define          SID_EQ_JAZZ                                      (unsigned short)0x008b       //Jazz                  [Function Index: 0008]
#define          SID_EQ_UNIQUE                                    (unsigned short)0x008c       //Unique                [Function Index: 0009]
#define          SID_EQ_CUSTOM                                    (unsigned short)0x008d       //Custom                [Function Index: 0010]
#define          SID_EQ_CUSTOM_EDIT                               (unsigned short)0x008e       //└ Edit               [Function Index: 0011]
#define          SID_EQ_NONE                                      (unsigned short)0x008f       //Normal                [Function Index: 0012]
#define          SID_SETTING_RADIO                                (unsigned short)0x0090       //FM Settings
#define          SID_RADIO_SCAN_SENSITIVITY                       (unsigned short)0x0091       //Scan Sensitivity
#define          SID_SCAN_SENSITIVITY_HIGH                        (unsigned short)0x0092       //High                  [Function Index: 0013]
#define          SID_SCAN_SENSITIVITY_LOW                         (unsigned short)0x0093       //Low                   [Function Index: 0014]
#define          SID_RADIO_STEREO_SWITCH                          (unsigned short)0x0094       //Stereo Switch
#define          SID_STEREO_SWITCH_OFF                            (unsigned short)0x0095       //Off                   [Function Index: 0015]
#define          SID_STEREO_SWITCH_ON                             (unsigned short)0x0096       //On                    [Function Index: 0016]
#define          SID_FM_REGION                                    (unsigned short)0x0097       //FM Region
#define          SID_FM_REGION_CHINA                              (unsigned short)0x0098       //China                 [Function Index: 0017]
#define          SID_FM_REGION_EUROPE                             (unsigned short)0x0099       //Europe                [Function Index: 0018]
#define          SID_FM_REGION_JAPAN                              (unsigned short)0x009a       //Japan                 [Function Index: 0019]
#define          SID_FM_REGION_USA                                (unsigned short)0x009b       //U.S.A.                [Function Index: 0020]
#define          SID_SETTING_RECORD                               (unsigned short)0x009c       //Record Settings
#define          SID_REC_QUALITY                                  (unsigned short)0x009d       //REC Quality
#define          SID_REC_HIGH_QUALITY                             (unsigned short)0x009e       //High Quality          [Function Index: 0021]
#define          SID_REC_NORMAL_QUALITY                           (unsigned short)0x009f       //Normal Quality        [Function Index: 0022]
#define          SID_REC_FORMAT                                   (unsigned short)0x00a0       //Record Format
#define          SID_REC_FORMAT_MP3                               (unsigned short)0x00a1       //MP3                   [Function Index: 0023]
#define          SID_REC_FORMAT_WAV                               (unsigned short)0x00a2       //WAV                   [Function Index: 0024]
#define          SID_SETTING_BT                                   (unsigned short)0x00a3       //Bluetooth Settings   
#define          SID_BT_ON                                        (unsigned short)0x00a4       //BT On                 [Function Index: 0025]
#define          SID_BT_OFF                                       (unsigned short)0x00a5       //BT Off                [Function Index: 0026]
#define          SID_BT_INFO                                      (unsigned short)0x00a6       //BT Information        [Function Index: 0027]
#define          SID_SETTING_PIC                                  (unsigned short)0x00a7       //Picture Settings   
#define          SID_PIC_AUTO_PLAY_TIME                           (unsigned short)0x00a8       //Auto Play Time
#define          SID_PIC_AUTO_PLAY_1S                             (unsigned short)0x00a9       //2 s                   [Function Index: 0028]
#define          SID_PIC_AUTO_PLAY_2S                             (unsigned short)0x00aa       //4 s                   [Function Index: 0029]
#define          SID_PIC_AUTO_PLAY_3S                             (unsigned short)0x00ab       //6 s                   [Function Index: 0030]
#define          SID_PIC_AUTO_PLAY_4S                             (unsigned short)0x00ac       //8 s                   [Function Index: 0031]
#define          SID_PIC_AUTO_PLAY_5S                             (unsigned short)0x00ad       //10 s                  [Function Index: 0032]
#define          SID_SETTING_TEXT                                 (unsigned short)0x00ae       //Text Settings   
#define          SID_TEXT_AUTO_PLAY_TIME                          (unsigned short)0x00af       //Auto Play Time
#define          SID_TEXT_AUTO_PLAY_1S                            (unsigned short)0x00b0       //2 s                   [Function Index: 0033]
#define          SID_TEXT_AUTO_PLAY_2S                            (unsigned short)0x00b1       //4 s                   [Function Index: 0034]
#define          SID_TEXT_AUTO_PLAY_3S                            (unsigned short)0x00b2       //6 s                   [Function Index: 0035]
#define          SID_TEXT_AUTO_PLAY_4S                            (unsigned short)0x00b3       //8 s                   [Function Index: 0036]
#define          SID_TEXT_AUTO_PLAY_5S                            (unsigned short)0x00b4       //10 s                  [Function Index: 0037]
#define          SID_SETTING_USB                                  (unsigned short)0x00b5       //USB Settings   
#define          SID_USB_DEVICE_MSC                               (unsigned short)0x00b6       //USB MSC mode          [Function Index: 0038]
#define          SID_USB_DEVICE_AUDIO                             (unsigned short)0x00b7       //USB Audio mode        [Function Index: 0039]
#define          SID_SETTING_COMMON                               (unsigned short)0x00b8       //Common Settings
#define          SID_COMMON_SCREEN_OFF_TIMER                      (unsigned short)0x00b9       //Screen Off Timer
#define          SID_SCREEN_OFF_15_SEC                            (unsigned short)0x00ba       //15 Seconds            [Function Index: 0040]
#define          SID_SCREEN_OFF_30_SEC                            (unsigned short)0x00bb       //30 Seconds            [Function Index: 0041]
#define          SID_SCREEN_OFF_1_MIN                             (unsigned short)0x00bc       //1 Minute              [Function Index: 0042]
#define          SID_SCREEN_OFF_3_MIN                             (unsigned short)0x00bd       //3 Minutes             [Function Index: 0043]
#define          SID_SCREEN_OFF_5_MIN                             (unsigned short)0x00be       //5 Minutes             [Function Index: 0044]
#define          SID_SCREEN_OFF_30_MIN                            (unsigned short)0x00bf       //30 Minutes            [Function Index: 0045]
#define          SID_COMMON_BRIGHTNESS                            (unsigned short)0x00c0       //Brightness
#define          SID_LUM_1                                        (unsigned short)0x00c1       //1                     [Function Index: 0046]
#define          SID_LUM_2                                        (unsigned short)0x00c2       //2                     [Function Index: 0047]
#define          SID_LUM_3                                        (unsigned short)0x00c3       //3                     [Function Index: 0048]
#define          SID_LUM_4                                        (unsigned short)0x00c4       //4                     [Function Index: 0049]
#define          SID_LUM_5                                        (unsigned short)0x00c5       //5                     [Function Index: 0050]
#define          SID_SYS_ABOUT                                    (unsigned short)0x00c6       //Information           [Function Index: 0051]
#define          SID_LANGUAGE                                     (unsigned short)0x00c7       //Language
#define          SID_CHINESE_S                                    (unsigned short)0x00c8       //简体中文              [Function Index: 0052]
#define          SID_CHINESE_T                                    (unsigned short)0x00c9       //繁體中文              [Function Index: 0053]
#define          SID_ENGLISH                                      (unsigned short)0x00ca       //English               [Function Index: 0054]
#define          SID_KOREAN                                       (unsigned short)0x00cb       //??                    [Function Index: 0055]
#define          SID_JAPANESE                                     (unsigned short)0x00cc       //日本語                [Function Index: 0056]
#define          SID_FRENCH                                       (unsigned short)0x00cd       //Fran?ais              [Function Index: 0057]
#define          SID_GERMAN                                       (unsigned short)0x00ce       //Deutsch               [Function Index: 0058]
#define          SID_PORTUGUESE                                   (unsigned short)0x00cf       //Português            [Function Index: 0059]
#define          SID_RUSSIAN                                      (unsigned short)0x00d0       //Русский        [Function Index: 0060]
#define          SID_SWEDISH                                      (unsigned short)0x00d1       //Svenska               [Function Index: 0061]
#define          SID_THAI                                         (unsigned short)0x00d2       //???????               [Function Index: 0062]
#define          SID_POLISH                                       (unsigned short)0x00d3       //j?zyk polski          [Function Index: 0063]
#define          SID_DENISH                                       (unsigned short)0x00d4       //Dansk                 [Function Index: 0064]
#define          SID_HOLLANDS                                     (unsigned short)0x00d5       //Hollands              [Function Index: 0065]
#define          SID_GREEK                                        (unsigned short)0x00d6       //Ελληνικ?       [Function Index: 0066]
#define          SID_CZECHIC                                      (unsigned short)0x00d7       //?í?tina              [Function Index: 0067]
#define          SID_TURKISH                                      (unsigned short)0x00d8       //Türk?e               [Function Index: 0068]
#define          SID_HEBREW                                       (unsigned short)0x00d9       //?????, ????           [Function Index: 0069]
#define          SID_ARABIC                                       (unsigned short)0x00da       //Arabic                [Function Index: 0070]
#define          SID_SETTING_INITIALIZE                           (unsigned short)0x00db       //Initialize
#define          SID_SYS_DEFAULT_SET                              (unsigned short)0x00dc       //Reset All Settings    [Function Index: 0071]
#define          SID_FORMAT_DISK                                  (unsigned short)0x00dd       //Format                [Function Index: 0072]
#define          SID_FORMAT_SDCARD                                (unsigned short)0x00de       //Format SD Card        [Function Index: 0073]





//-----------------------------------------------------------------------------------------------------------------------------
#define          SID_SETTINGS_ENTRY                               SID_SETTINGS       //Settings
#define          SID_SETTINGS_ENTRY_FUN_COUNTER                   0x004a


#endif
